channels:
- conda-forge
- defaults
dependencies:
- simplekml
- h5py
- matplotlib
- pybase64
- IPython
- scipy
- seaborn
- pyproj
- pprintpp
- geopandas
- shapely
- astropy
- laspy
- pandas
- hdbscan
- ipywidgets
- pathlib
- ipyfilechooser
- tqdm
- sliderule
- numpy
- bokeh
- ipyleaflet
- fast-histogram
name: openoceans
pip:
- progressbar2
- waipy
